# Getting and Knowing your Data

In this assignment, we keep practicing `pandas` skills.

# Exercise 1 (2 points)

Import the `pandas` and `numpy` libraries.

In [1]:
# Exercise 1
import pandas as pd
import numpy as np

# Exercise 2 (2 points)

Create a data-frame called `users` and use `user_id` as index.

In [3]:
# Exercise 2
users = pd.read_csv("users.csv", sep="|", index_col="user_id")

# Exercise 3 (2 points)

Print the first 25 rows from the `users` data-frame.

In [4]:
# Exercise 3
users.head(25)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

# Exercise 4 (2 points)

Print the last 10 rows from the `users` data-frame.

In [5]:
# Exercise 4
users.tail(10)

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

# Exercise 5 (2 points)

Report the number of rows and columns in the `users` data-frame.

In [6]:
# Exercise 5
users.shape

(943, 4)

# Exercise 6 (2 points)

Report the data type of each column.

In [7]:
# Exercise 6
users.dtypes

age           int64
gender          str
occupation      str
zip_code        str
dtype: object

# Exercise 7 (2 points)

Print only the `occupation` column.

In [8]:
# Exercise 7
users["occupation"]

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: str

# Exercise 8 (2 points)

How many different occupations are in this dataset?

In [9]:
# Exercise 8
users["occupation"].nunique()

21

# Exercise 9 (2 points)

What is the most frequent occupation?

In [10]:
# Exercise 9
users["occupation"].value_counts().head(1)

occupation
student    196
Name: count, dtype: int64

# Exercise 10 (2 points)

Summarize the `users` data-frame.

In [11]:
# Exercise 10
users.describe()

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

# Exercise 11 (2 points)

Summarize all the columns from the `users` data-frame.

In [12]:
# Exercise 11
users.describe(include="all")

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

# Exercise 12 (2 points)

What is the mean `age` of users?

In [13]:
# Exercise 12
users["age"].mean()

np.float64(34.05196182396607)

# Exercise 13 (2 points)

Report the mean `age` of female and male users.

In [14]:
# Exercise 13
users.groupby("gender")["age"].mean()

gender
F    33.813187
M    34.149254
Name: age, dtype: float64